import { MORE_MISCONCEPTIONS } from "./misconceptions2";
import type { Misconception } from "./types";

const MATH_MISCONCEPTIONS: Misconception[] = [
  {
    id: "inverse-op",
    conceptId: "linear-equations",
    label: "Incorrect inverse operation",
    errorType: "procedural",
    description: "Undoes the operations in the wrong way when isolating x, for example subtracting the coefficient instead of dividing by it.",
    patternSummary: "you're making mistakes when isolating variables",
    defaultStrategy: "step-by-step",
    explanations: {
      "step-by-step": "Work in two moves. First undo the + or − on both sides. Then undo the multiplication by dividing. A number stuck to x is removed by dividing, never by subtracting.",
      analogy: "Solving an equation is like unwrapping a gift: whatever was wrapped last comes off first. x was multiplied, then a number was added, so remove the add, then the multiply.",
      example: "Look at 2x + 1 = 9. Subtract 1 to get 2x = 8. Divide by 2 to get x = 4. The 2 disappears by dividing, not by subtracting.",
      visual: "Picture a balance scale. 3x + 4 = 19 is three x-blocks and 4 loose ones on one side. Take 4 away from both sides, then split the 15 into 3 equal stacks.",
    },
    example: { problem: "2x + 1 = 9", steps: ["Subtract 1 from both sides: 2x = 8", "Divide both sides by 2: x = 4", "Check: 2 × 4 + 1 = 9"] },
    guidedQuestionId: "g-inverse-op",
  },
  {
    id: "sign-error",
    conceptId: "linear-equations",
    label: "Sign error when moving terms",
    errorType: "procedural",
    description: "Moves a term to the other side without changing its operation, so + becomes + again instead of −.",
    patternSummary: "a term changes sign the wrong way when it crosses the equals sign",
    defaultStrategy: "visual",
    explanations: {
      "step-by-step": "To remove + 4 from one side, subtract 4 from both sides. To remove − 4, add 4 to both sides. Always do the opposite, on both sides.",
      analogy: "Think of walking 4 steps forward. To get back to where you started you walk 4 steps backward, so the opposite move always cancels.",
      example: "x − 5 = 3. To cancel − 5 add 5 to both sides: x = 8. Check: 8 − 5 = 3.",
      visual: "On a balance scale, taking 4 off one side and nothing off the other tips it. Whatever you remove or add, do the same on both sides.",
    },
    example: { problem: "x − 5 = 3", steps: ["Cancel − 5 by adding 5 to both sides", "x = 3 + 5 = 8", "Check: 8 − 5 = 3"] },
    guidedQuestionId: "g-sign-error",
  },
  {
    id: "fraction-parts",
    conceptId: "fractions",
    label: "Adds numerators and denominators separately",
    errorType: "conceptual",
    description: "Treats the top and bottom of a fraction as unrelated numbers, so 1/2 + 1/3 becomes 2/5.",
    patternSummary: "you're combining the tops and bottoms of fractions as separate numbers",
    defaultStrategy: "visual",
    explanations: {
      "step-by-step": "First make the denominators match. Then add only the numerators and keep the denominator the same. The denominator names the size of the pieces, so it does not add.",
      analogy: "Half a pizza plus a quarter pizza is not two slices out of six. You have to cut both into the same size slices before counting them.",
      example: "1/2 + 1/4: rewrite 1/2 as 2/4. Now 2/4 + 1/4 = 3/4. The pieces are all quarters, so the bottom stays 4.",
      visual: "Draw a bar split in halves and another split in quarters. Shade 1/2 and 1/4 on a quarter-bar: 2 shaded pieces plus 1 more piece is 3 quarters.",
    },
    example: { problem: "1/2 + 1/4", steps: ["Rewrite 1/2 as 2/4", "Add the numerators: 2 + 1 = 3", "Keep the denominator: 3/4"] },
    guidedQuestionId: "g-fraction-parts",
  },
  {
    id: "percent-shift",
    conceptId: "percentages",
    label: "Misplaced decimal when converting a percent",
    errorType: "procedural",
    description: "Uses 10 or 0.01 instead of 0.10 as the multiplier, so answers are 10× too big or too small.",
    patternSummary: "the percent isn't being converted to a decimal correctly",
    defaultStrategy: "example",
    explanations: {
      "step-by-step": "Step one: divide the percent by 100 to get a decimal (20% is 0.20). Step two: multiply by the amount. Check the size: 20% should be a fifth of the amount.",
      analogy: "A percent is a price per hundred. 20% means 20 cents of every dollar, so 20% of $150 is 20 cents on each of 150 dollars, not 20 dollars each.",
      example: "10% of 80: 10 ÷ 100 = 0.10, and 0.10 × 80 = 8. Sense check: 8 is a tenth of 80.",
      visual: "Picture a 10 × 10 grid. 20% shades 20 of the 100 squares, one in five. So the answer is a fifth of the amount.",
    },
    example: { problem: "10% of 80", steps: ["10% = 10 ÷ 100 = 0.10", "0.10 × 80 = 8", "Sense check: 8 is one tenth of 80"] },
    guidedQuestionId: "g-percent-shift",
  },
  {
    id: "additive-ratio",
    conceptId: "ratios",
    label: "Adds instead of scaling",
    errorType: "conceptual",
    description: "Keeps the difference between parts rather than the multiplier, so 2:3 with 6 blue becomes 6:7.",
    patternSummary: "you're adding a fixed amount where the ratio needs multiplication",
    defaultStrategy: "analogy",
    explanations: {
      "step-by-step": "Find the multiplier: how many times bigger is the new part? Then multiply every other part by the same number. Never add the same amount to each part.",
      analogy: "Think of a recipe photocopied at 300%. Every ingredient triples. Adding 4 cups to everything would change the flavour, tripling keeps it identical.",
      example: "2 : 3 with 6 parts blue. 2 × 3 = 6, so multiply white by 3 too: 3 × 3 = 9. The ratio is now 6 : 9, the same as 2 : 3.",
      visual: "Draw 2 blue and 3 white blocks. To reach 6 blue, repeat that whole group 3 times. You get 9 white blocks.",
    },
    example: { problem: "2 : 3 = 6 : ?", steps: ["2 × 3 = 6, so the multiplier is 3", "Multiply the second part: 3 × 3 = 9", "Check: 6 : 9 simplifies to 2 : 3"] },
    guidedQuestionId: "g-additive-ratio",
  },
  {
    id: "function-substitution",
    conceptId: "functions",
    label: "Wrong order when substituting into f(x)",
    errorType: "procedural",
    description: "Substitutes correctly but applies operations in the wrong order, or evaluates when it should solve.",
    patternSummary: "the order of operations slips after you substitute the input",
    defaultStrategy: "step-by-step",
    explanations: {
      "step-by-step": "Replace every x with the input in brackets. Then follow the order of operations: powers, multiplication, then addition or subtraction.",
      analogy: "A function is a machine with a fixed recipe. The input goes in, and each step of the recipe happens in order: multiply first, then add.",
      example: "f(x) = 2x + 1 at x = 3. Write 2(3) + 1. Multiply first: 6. Then add: 7.",
      visual: "Draw a machine: input 3 goes into a box that says 'times 2', then a box that says 'plus 1'. The output is 7.",
    },
    example: { problem: "f(x) = 2x + 1, find f(3)", steps: ["Substitute: 2(3) + 1", "Multiply first: 6 + 1", "Add: 7"] },
    guidedQuestionId: "g-function-substitution",
  },
  {
    id: "word-translation",
    conceptId: "word-problems",
    label: "Difficulty translating words into an equation",
    errorType: "conceptual",
    description: "Understands the arithmetic but misreads the order or operations described in the sentence.",
    patternSummary: "the maths is fine, but the words aren't becoming the right equation",
    defaultStrategy: "analogy",
    explanations: {
      "step-by-step": "Underline the unknown, then translate phrase by phrase: twice a number is 2x, 5 more than is + 5, is means =. Build the equation first, solve second.",
      analogy: "Word problems are a story with a hidden equation. Read it like a receipt: a fixed fee is a constant, a per-item price multiplies the unknown.",
      example: "A taxi charges $3 plus $2 per km: cost = 3 + 2k. If the trip costs $9, then 3 + 2k = 9, so k = 3.",
      visual: "Sketch the story as a bar: a small block for the fixed part and equal blocks for each repeat. The total is the sum of all blocks.",
    },
    example: { problem: "Twice a number plus 3 is 11", steps: ["Twice a number → 2x", "Plus 3 → + 3, and is → =", "Equation: 2x + 3 = 11, so x = 4"] },
    guidedQuestionId: "g-word-translation",
  },
  {
    id: "area-perimeter",
    conceptId: "basic-geometry",
    label: "Confuses area with perimeter",
    errorType: "conceptual",
    description: "Uses the perimeter formula when area is asked (or the reverse), often because both involve the same side lengths.",
    patternSummary: "area and perimeter are being swapped",
    defaultStrategy: "visual",
    explanations: {
      "step-by-step": "Ask first: am I measuring around the edge (perimeter, add sides) or the space inside (area, multiply)? Choose the formula after answering that.",
      analogy: "Perimeter is the fence around a garden. Area is the grass inside it. You buy fence by length, and grass seed by covered space.",
      example: "A 5 by 3 rectangle. Perimeter = 5 + 3 + 5 + 3 = 16. Area = 5 × 3 = 15. Same shape, different question.",
      visual: "Draw a 5 by 3 grid. Count squares inside: that is the area, 15. Trace the outline: that is the perimeter, 16.",
    },
    example: { problem: "Rectangle 5 by 3", steps: ["Perimeter: 5 + 3 + 5 + 3 = 16 (around the edge)", "Area: 5 × 3 = 15 (space inside)", "Different questions, different formulas"] },
    guidedQuestionId: "g-area-perimeter",
  },
];

export const MISCONCEPTIONS: Misconception[] = [...MATH_MISCONCEPTIONS, ...MORE_MISCONCEPTIONS];

export const misconceptionById = (id: string) => MISCONCEPTIONS.find((m) => m.id === id);
export const misconceptionsFor = (conceptId: string) => MISCONCEPTIONS.filter((m) => m.conceptId === conceptId);
export const misconceptionLabel = (id: string) => misconceptionById(id)?.label ?? id.replace(/^other-/, "").replace(/-/g, " ");
