import type { Misconception } from "./types";

export const MORE_MISCONCEPTIONS: Misconception[] = [
  {
    id: "assignment-confusion",
    conceptId: "variables",
    label: "Reads = as maths equals",
    errorType: "conceptual",
    description: "Thinks a variable stays linked to another variable, or reads x = x + 2 as an impossible equation instead of an instruction.",
    patternSummary: "the equals sign is being read as maths equals instead of store this value",
    defaultStrategy: "analogy",
    explanations: {
      "step-by-step": "Read an assignment right to left. First work out the right side using the current values. Then store the result in the name on the left.",
      analogy: "A variable is a labeled box. x = x + 2 means: look inside the box, add 2, and put the new number back in the same box.",
      example: "x = 5, then x = x + 2. Right side: 5 + 2 = 7. Store 7 in x. Now x is 7.",
      visual: "Picture the box named x holding a 5. The line lifts the 5 out, adds 2, and drops a 7 back in.",
    },
    example: { problem: "x = 5, then x = x + 2", steps: ["Work out the right side: 5 + 2 = 7", "Store 7 in the box named x", "x is now 7"] },
    guidedQuestionId: "g-assignment-confusion",
  },
  {
    id: "off-by-one",
    conceptId: "loops",
    label: "Off-by-one in loops",
    errorType: "procedural",
    description: "Counts loop passes from 1 to n instead of 0 to n minus 1, so a count or last value is off by one.",
    patternSummary: "loops are being counted from one instead of from zero",
    defaultStrategy: "visual",
    explanations: {
      "step-by-step": "range(n) starts at 0 and stops before n. So range(3) gives 0, 1, 2. That is three passes.",
      analogy: "Think of building floors: the ground floor is 0. Three floors are 0, 1 and 2.",
      example: "range(4) gives 0, 1, 2, 3. Four passes, and the last number is 3, not 4.",
      visual: "Watch the counter: it starts at zero, goes up by one each pass, and stops before it reaches n.",
    },
    example: { problem: "for i in range(3): print(i)", steps: ["Pass one prints 0", "Pass two prints 1", "Pass three prints 2, then it stops"] },
    guidedQuestionId: "g-off-by-one",
  },
  {
    id: "boundary-condition",
    conceptId: "conditions",
    label: "Mixes up > and >=",
    errorType: "procedural",
    description: "Treats greater-than and greater-than-or-equal the same, or checks a condition against an out-of-date value.",
    patternSummary: "the edge case, where the value equals the limit, is being missed",
    defaultStrategy: "example",
    explanations: {
      "step-by-step": "Ask: is the value exactly equal to the limit? With >= that counts as true. With > it does not.",
      analogy: "A sign says 18 and over (>=) or over 18 (>). Someone who is exactly 18 gets in only with the first sign.",
      example: "n = 10. n >= 10 is true. n > 10 is false, because 10 is not more than 10.",
      visual: "Put the value on a number line. The limit is a point. >= includes the point, and > leaves it out.",
    },
    example: { problem: "n = 10. Compare n > 10 and n >= 10", steps: ["n > 10: is 10 more than 10? No, false", "n >= 10: is 10 at least 10? Yes, true", "The edge case decides the path"] },
    guidedQuestionId: "g-boundary-condition",
  },
  {
    id: "one-based-index",
    conceptId: "lists",
    label: "Counts list positions from one",
    errorType: "procedural",
    description: "Thinks the first item is at position 1, so every index lands one item too far along.",
    patternSummary: "list positions are being counted from one instead of from zero",
    defaultStrategy: "visual",
    explanations: {
      "step-by-step": "The index is how many steps you are from the start. The first item is 0 steps away, so its index is 0.",
      analogy: "A ruler starts at 0, not 1. The first mark is where you begin, and each item is a step further.",
      example: "list = [10, 20, 30]. list[0] is 10, list[1] is 20, list[2] is 30.",
      visual: "Look at the index tags under the cells: 0, 1, 2. The first cell is labeled 0.",
    },
    example: { problem: "list = [10, 20, 30]", steps: ["list[0] is the first item: 10", "list[1] is the second item: 20", "list[2] is the third item: 30"] },
    guidedQuestionId: "g-one-based-index",
  },
  {
    id: "continent-count",
    conceptId: "continents",
    label: "Miscounts continents and oceans",
    errorType: "conceptual",
    description: "Merges or drops a continent or ocean, for example forgetting Antarctica or the Southern Ocean.",
    patternSummary: "one continent or ocean is being left out",
    defaultStrategy: "analogy",
    explanations: {
      "step-by-step": "Name them one at a time and count as you go. Continents: Asia, Africa, Europe, North America, South America, Australia, Antarctica. Oceans: Pacific, Atlantic, Indian, Southern, Arctic.",
      analogy: "Imagine going round the globe with a checklist, ticking each landmass and each sea. The cold bottom has both a continent and an ocean.",
      example: "Seven continents, five oceans. The easy ones to forget are Antarctica and the Southern Ocean.",
      visual: "Look at the blocks: seven pieces of land, and five patches of sea around them.",
    },
    example: { problem: "Count the continents", steps: ["Asia, Africa, Europe: 3", "North America, South America: 5", "Australia and Antarctica: 7"] },
    guidedQuestionId: "g-continent-count",
  },
  {
    id: "lat-long-mixup",
    conceptId: "latlon",
    label: "Mixes up latitude and longitude",
    errorType: "conceptual",
    description: "Confuses latitude (north-south, 0 at the Equator, up to 90) with longitude (east-west, a full 360 around).",
    patternSummary: "latitude and longitude are getting swapped",
    defaultStrategy: "visual",
    explanations: {
      "step-by-step": "Latitude measures north and south, from 0 at the Equator to 90 at each pole. Longitude measures east and west, from 0 at the Prime Meridian, and goes a full 360 around.",
      analogy: "Latitude is like floors in a building, going up or down from the ground. Longitude is like walking around the building.",
      example: "Equator: latitude 0. North Pole: latitude 90. Prime Meridian: longitude 0. All the way around: 360.",
      visual: "Latitude lines run flat, east to west, stacked from the Equator up to the pole. Longitude lines run top to bottom, all the way around.",
    },
    example: { problem: "Where is 0, 0?", steps: ["Latitude 0 is the Equator", "Longitude 0 is the Prime Meridian", "They cross at 0, 0"] },
    guidedQuestionId: "g-lat-long-mixup",
  },
  {
    id: "time-direction",
    conceptId: "timezones",
    label: "Mixes up ahead and behind",
    errorType: "conceptual",
    description: "Subtracts hours when going east, or adds when going west. East is always later, west is always earlier.",
    patternSummary: "east and west are pointing the wrong way for time",
    defaultStrategy: "analogy",
    explanations: {
      "step-by-step": "Ask: is the place east or west? East is later, so add hours. West is earlier, so subtract hours.",
      analogy: "The sun rises in the east first. So places to the east are already further into the day.",
      example: "12:00 in London. 3 hours east: add, so 15:00. 5 hours west: subtract, so 07:00.",
      visual: "Line the cities up west to east. The clocks read later as you move east, and earlier as you move west.",
    },
    example: { problem: "12:00 in London, 3 hours east", steps: ["East is later", "12 + 3 = 15", "It is 15:00 there"] },
    guidedQuestionId: "g-time-direction",
  },
  {
    id: "scale-direction",
    conceptId: "scale",
    label: "Applies the map scale backwards",
    errorType: "procedural",
    description: "Divides when converting map distance to real distance, or multiplies when converting back.",
    patternSummary: "the map scale is being applied in the wrong direction",
    defaultStrategy: "example",
    explanations: {
      "step-by-step": "Map to real: multiply by the scale. Real to map: divide by the scale. Check the size: real distances should be bigger than map distances.",
      analogy: "A map is a shrunken world. To get back to the real world you have to grow it, so you multiply.",
      example: "1 cm = 10 km. A road 4 cm long on the map is 4 × 10 = 40 km. Going back, 40 km ÷ 10 = 4 cm.",
      visual: "Each centimetre on the map stacks up into a big block of real kilometres. More blocks, more distance.",
    },
    example: { problem: "1 cm = 10 km. A road is 4 cm on the map", steps: ["Each cm is 10 km", "4 × 10 = 40", "The road is 40 km"] },
    guidedQuestionId: "g-scale-direction",
  },
];
